spring.datasource.url=jdbc:postgresql://localhost:5432/blooddonation
spring.datasource.username=postgres
spring.datasource.password=wizard


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Redis Configuration
spring.data.redis.url=${REDIS_URL:redis://localhost:6379}


spring.cache.type=redis


# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:}
spring.kafka.properties.sasl.jaas.config=${KAFKA_SASL_JAAS_CONFIG:}
spring.kafka.consumer.group-id=pulsenode-group
spring.kafka.consumer.auto-offset-reset=earliest

